sudo: required

language: c

dist: xenial

services:
  - docker

env:
  global:
    - BUILD_IMAGE="ergw/capwap-dp"
    - DOCKER_USERNAME="ergwci"
    - secure: "wuvFs1iFyUY4qgmDhXXwcTkISsOht0q5BvXRg/LKpN7Vx9Q+4f0CWc1viNgOWxdlCCV86sYYSfTg6d45xGwhcwM7PpSjCW6qWT3MIukZjua0jE67LNo+J84sC7QqWESvSB/BZ++OoX1e72Z9uiIaolKew7KLAiMlwzr038lJpbfueEj3SixKNGEXlxG41fnWZCfNsaHvto2k95Sq+oEFCowT9OEbARz1YW2it9t24yxRkzwbr7bN6UMbe4RCvGD5Kkwtrm2NSNBAj9Ntkrybd8ZzhcGOy/hZQQSTU+xLX7LJpQ56/ZSu6dFh03BZct2kMvsHObTNxhnUXEh+T1hEUB24XVTmUUrxKyfbjNjn1DgdUFM9KH9dGuQ+S1W+UyCn+5Ph46cvvJIRmB5dxgYYFsmSob4qtLaDfno2cHjNdKKIbe4JXJ9AsGECe/w8DNBPk6iX+jmFnopPabqJwOP7moaM2OygEFAPigbfY9FQ6++/Jz85MMPY+zR3RuECBvYYPbOG1TUxg51wnn7xv/GhnRT+/dCcGPhsOiSKR2OqwCkdboH+G72KPTpsLnyP5Ln40CFWO9DkVgdjEMZ7oyiMUqNSVfClZ1iZXYWqiYfCdMUiDkhAWf64iv2FgTTxkTF8qZlM++3vpfLQNZtQLvLFpXz/m5BTdug1X10rLsIUL38="

script:
  - export TAG=`if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then echo PR-$TRAVIS_PULL_REQUEST_BRANCH ; else echo $TRAVIS_BRANCH ; fi`
  - if [ "$TAG" == "master" ]; then export TAG="latest"; fi
  - docker build -t $BUILD_IMAGE:$TAG -f docker/Dockerfile .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $BUILD_IMAGE:$TAG
  - echo "docker push done"

branches:
  only:
    - master
