sudo: true

language: c

compiler:
  - clang
  - gcc

services:
  - docker

env:
  global:
    - BUILD_IMAGE="ergw/capwap-dp"
    - DOCKER_USERNAME="ergwci"
    - secure: "wuvFs1iFyUY4qgmDhXXwcTkISsOht0q5BvXRg/LKpN7Vx9Q+4f0CWc1viNgOWxdlCCV86sYYSfTg6d45xGwhcwM7PpSjCW6qWT3MIukZjua0jE67LNo+J84sC7QqWESvSB/BZ++OoX1e72Z9uiIaolKew7KLAiMlwzr038lJpbfueEj3SixKNGEXlxG41fnWZCfNsaHvto2k95Sq+oEFCowT9OEbARz1YW2it9t24yxRkzwbr7bN6UMbe4RCvGD5Kkwtrm2NSNBAj9Ntkrybd8ZzhcGOy/hZQQSTU+xLX7LJpQ56/ZSu6dFh03BZct2kMvsHObTNxhnUXEh+T1hEUB24XVTmUUrxKyfbjNjn1DgdUFM9KH9dGuQ+S1W+UyCn+5Ph46cvvJIRmB5dxgYYFsmSob4qtLaDfno2cHjNdKKIbe4JXJ9AsGECe/w8DNBPk6iX+jmFnopPabqJwOP7moaM2OygEFAPigbfY9FQ6++/Jz85MMPY+zR3RuECBvYYPbOG1TUxg51wnn7xv/GhnRT+/dCcGPhsOiSKR2OqwCkdboH+G72KPTpsLnyP5Ln40CFWO9DkVgdjEMZ7oyiMUqNSVfClZ1iZXYWqiYfCdMUiDkhAWf64iv2FgTTxkTF8qZlM++3vpfLQNZtQLvLFpXz/m5BTdug1X10rLsIUL38="

script:
  - docker run -v `pwd`:/build --name capwap-dp-build ubuntu:16.04
    sh -c "
       apt-get -qq update &&
       apt-get -y install build-essential automake autoconf libtool pkg-config shtool libev-dev libsystemd-dev erlang-dev liburcu-dev libconfig-dev &&
       cd /build &&
       ./autogen.sh &&
       ./configure --sysconfdir=/etc &&
       make &&
       make install
    "
  - docker commit capwap-dp-build capwap-dp-build

after_success:
  - docker create --name capwap-dp capwap-dp-build /usr/bin/capwap-dp
  - docker commit capwap-dp $BUILD_IMAGE
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - export TAG=`if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then echo PR-$TRAVIS_PULL_REQUEST_BRANCH ; else echo $TRAVIS_BRANCH ; fi`
  - if [ "$TAG" == "master" ]; then export TAG="latest"; fi
  - docker tag $BUILD_IMAGE $BUILD_IMAGE:$TAG
  - docker push $BUILD_IMAGE:$TAG
  - echo "docker push done"

before_install:
  - docker pull ubuntu:16.04

branches:
  only:
    - master
